In [1]:
from vivarium.simulator.api import SimulatorServer

/Users/moulinfr/Documents/dev/vivarium/env_vivarium/lib/python3.8/site-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(


In [2]:
simulator = SimulatorServer()

In [6]:
from urllib.parse import urljoin
urljoin?

Signature: urljoin(base, url, allow_fragments=True)
Docstring:
Join a base URL and a possibly relative URL to form an absolute
interpretation of the latter.
File:      ~/Documents/dev/vivarium/env_vivarium/lib/python3.8/urllib/parse.py
Type:      function

In [3]:
simulator.is_started()

http://127.0.0.1:5000/simulator/is_started


False

In [6]:
simulator.start_sim()

In [7]:
simulator.stop_sim()

In [20]:
simulator.set_motors(3, [-0.1, 1.])

In [8]:
simulator.get_sim_state()

{'OBSTACLE': {'diameters': [10.0, 10.0],
  'entity_type': 3,
  'positions': [[13.544201850891113, 22.679758071899414],
   [17.045581817626953, 68.9339599609375]],
  'thetas': [6.274595737457275, 0.6592649817466736]},
 'PREDATOR': {'entity_type': 2,
  'positions': [[66.01316833496094, 89.28498840332031],
   [45.26231384277344, 54.75857162475586]],
  'thetas': [5.156526565551758, 4.307538986206055]},
 'PREY': {'entity_type': 1,
  'positions': [[45.13328170776367, 33.6268310546875],
   [27.926136016845703, 40.805625915527344],
   [72.78527069091797, 53.972923278808594],
   [53.501068115234375, 72.65196228027344],
   [20.6779842376709, 6.349802017211914],
   [91.55792236328125, 72.23006439208984],
   [59.16667175292969, 56.50968551635742],
   [36.828948974609375, 61.1683235168457],
   [45.62112045288086, 34.15275955200195],
   [82.01039123535156, 49.25001907348633],
   [15.4860258102417, 40.279354095458984],
   [50.31255340576172, 50.14752197265625],
   [97.54875946044922, 15.1829833984375

In [9]:
x = simulator.get_motors()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
print(x)

In [28]:
import numpy as np
from vivarium.simulator.simulator import sen
idx = 5
while True:
    state = simulator.get_sim_state()
    proxs = np.array(state['PREY']['positions'])[idx, :]
    motors = proxs
    simulator.set_motors(idx, motors)

KeyboardInterrupt: 

In [24]:
type(state['PREY']['positions'])

list

In [9]:
import numpy as np
def set_motors(agent_idx, motors):
    res = np.zeros((10, 2))
    print(res[agent_idx, :])
    res[agent_idx, :] = np.array(motors)
    #motor_input = jnp.array(res)
    
set_motors(0, [0,0])

[0. 0.]


In [52]:
import numpy as np
import jax.numpy as jnp
from jax import vmap

behaviors = jnp.array([[[1., 0., 0.], [0., 1., 0.]], [[0., 1., 0.], [1., 0., 0.]], [[0., -1., 1.], [-1., 0., 1.]]])
weights = jnp.array([1., 0.5, 1.])
#biases = jnp.array([0., 0., 1])

print(behaviors)


def weighted_behavior(w, b):
    f = vmap(lambda w, b: w * b)
    return f(w, b).sum(axis=0)

print(behaviors.shape)

#weighted_behavior = vmap(weighted_behavior, (0, 2))
#print('f', f(weights, behaviors))
print('wb', weighted_behavior(weights, behaviors).dot(jnp.array([1., 1., 1.])))

[[[ 1.  0.  0.]
  [ 0.  1.  0.]]

 [[ 0.  1.  0.]
  [ 1.  0.  0.]]

 [[ 0. -1.  1.]
  [-1.  0.  1.]]]
(3, 2, 3)
wb [1.5 1.5]


In [39]:
f1 = lambda biases, w, b: biases + w * b
f1(1, 1, jnp.array([[-1., 0.], [0., -1.]]))

Array([[0., 1.],
       [1., 0.]], dtype=float32)

In [60]:
def weighted_behavior(w, b):
    f = vmap(lambda w, b: w * b)
    return f(w, b).sum(axis=0)


def behavior(weights, behavior_map, proxs):
    return weighted_behavior(weights, behavior_map).dot(jnp.hstack((proxs, 1.)))

In [61]:
behavior(weights, behaviors, jnp.array([0, 0.]))

Array([1., 1.], dtype=float32)

In [59]:
jnp.hstack((jnp.array([0., 1.]), 2.))

Array([0., 1., 2.], dtype=float32)

In [21]:
import asyncio

In [8]:
async def main():
    await asyncio.sleep(1)
    print('hello')

asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop

In [8]:
import time

async def main():
    print("start")
    time.sleep(5)
    print("stop")
    
await main()

start
stop


In [3]:
import asyncio

async def hello():
  print('Hello')
  await asyncio.sleep(3)
  print('world')

await hello()

Hello
world
